criaCartao("Corinthians", "Quem é o maior artilheiro da história do Corinthians?", "Luan"),
    criaCartao("Corinthians", "Em que ano o Corinthians foi fundado?", "1910"),
    criaCartao("Corinthians", "Qual é o estádio do Corinthians?", "Arena Corinthians"),
    criaCartao("Corinthians", "Quantos títulos de Copa do Brasil o Corinthians tem?", "3"),
    criaCartao("Corinthians", "Quem foi o técnico do Corinthians que venceu a Libertadores de 2012?", "Tite"),
    criaCartao("Corinthians", "Quem é o jogador mais caro da história do Corinthians?", "Jadson"),
    criaCartao("Corinthians", "Quantos títulos mundiais o Corinthians tem?", "2"),
    criaCartao("Corinthians", "Qual foi a primeira competição internacional conquistada pelo Corinthians?", "Copa Sudamericana 2012"),
    criaCartao("Corinthians", "Quem é o maior ídolo da história do Corinthians?", "Sócrates"),
    criaCartao("Corinthians", "Quantas vezes o Corinthians venceu o Campeonato Brasileiro?", "7"),
    criaCartao("Corinthians", "Quem foi o capitão do Corinthians na conquista da Libertadores de 2012?", "Ralf"),
    criaCartao("Corinthians", "Qual é o mascote do Corinthians?", "Mosqueteiro"),
    criaCartao("Corinthians", "Em que ano o Corinthians conquistou o primeiro título da Copa do Mundo de Clubes?", "2000"),
    criaCartao("Corinthians", "Quem foi o artilheiro do Corinthians na Copa do Mundo de Clubes de 2012?", "Paulo Guerreiro"),
    criaCartao("Corinthians", "Qual foi o maior placar do Corinthians em uma final de Libertadores?", "2-0 contra o Boca Juniors"),
    criaCartao("Corinthians", "Quantos jogos o Corinthians ficou invicto durante a campanha do título da Libertadores de 2012?", "8 jogos"),
    criaCartao("Corinthians", "Quem foi o primeiro presidente do Corinthians?", "José Vicente de Azevedo"),
    criaCartao("Corinthians", "Quantos gols o Corinthians fez no Campeonato Paulista de 2019?", "73 gols"),
    criaCartao("Corinthians", "Quem fez o gol da vitória na final da Copa do Mundo de Clubes de 2000?", "Ronaldo Fenômeno"),
    criaCartao("Corinthians", "Qual jogador do Corinthians foi eleito melhor jogador da Copa Libertadores de 2012?", "Jorge Henrique"),
    criaCartao("Corinthians", "Quem é o maior artilheiro do Corinthians em clássicos contra o Palmeiras?", "Jairzinho"),
    criaCartao("Corinthians", "Quantos títulos do Campeonato Paulista o Corinthians conquistou até 2024?", "30 títulos"),
    criaCartao("Corinthians", "Qual a maior goleada da história do Corinthians no Campeonato Paulista?", "10-2 contra o Jaboticabal"),
    criaCartao("Corinthians", "Em que ano o Corinthians conquistou o Campeonato Mundial Interclubes pela segunda vez?", "2012"),
    criaCartao("Corinthians", "Quem foi o técnico que levou o Corinthians ao título de Campeão Brasileiro em 2015?", "Tite"),
    criaCartao("Corinthians", "Quem foi o goleiro titular do Corinthians no título da Libertadores de 2012?", "Cássio"),
    criaCartao("Corinthians", "Em que cidade o Corinthians foi fundado?", "São Paulo"),
    criaCartao("Corinthians", "Quantos títulos da Copa do Brasil o Corinthians tem até 2024?", "3 títulos"),
    criaCartao("Corinthians", "Qual jogador do Corinthians foi artilheiro do Campeonato Paulista de 2017?", "Jô"),
    criaCartao("Corinthians", "Qual foi o principal adversário do Corinthians na final da Libertadores de 2012?", "Boca Juniors"),
    criaCartao("Corinthians", "Quem foi o primeiro jogador a fazer gol no estádio Arena Corinthians?", "Danilo"),
    criaCartao("Corinthians", "Qual o nome do maior ídolo do Corinthians na década de 90?", "Ronaldo Fenômeno"),
    criaCartao("Corinthians", "Em que ano o Corinthians foi campeão do Campeonato Paulista após 23 anos sem conquistas?", "1995"),
    criaCartao("Corinthians", "Quem é o técnico que conquistou o título da Copa do Brasil de 2009?", "Mano Menezes"),
    criaCartao("Corinthians", "Quem fez o gol do Corinthians no primeiro título mundial, em 2000?", "Ronaldo Fenômeno"),
    criaCartao("Corinthians", "Qual é o nome do maior rival do Corinthians?", "Palmeiras"),
    criaCartao("Corinthians", "Em qual campeonato o Corinthians conquistou seu primeiro título internacional?", "Copa Rio Internacional 1953"),
    criaCartao("Corinthians", "Qual é o nome do famoso camisa 10 do Corinthians, ídolo da década de 80?", "Sócrates"),
    criaCartao("Corinthians", "Quem foi o jogador do Corinthians que mais atuou em Copas do Mundo?", "Cássio"),
    criaCartao("Corinthians", "Em que ano o Corinthians foi campeão da Copa Sul-Americana?", "2015"),
    criaCartao("Corinthians", "Qual o maior clássico do futebol paulista?", "Corinthians x Palmeiras"),
    criaCartao("Corinthians", "Quem foi o artilheiro do Corinthians no Campeonato Brasileiro de 2017?", "Jô"),
    criaCartao("Corinthians", "Quem é o jogador que mais fez gols com a camisa do Corinthians?", "Luan"),
    criaCartao("Corinthians", "Qual é o nome do estádio onde o Corinthians joga?", "Arena Corinthians"),
    criaCartao("Corinthians", "Quantos gols o Corinthians fez na final da Libertadores de 2012?", "2 gols"),
    criaCartao("Corinthians", "Qual é o lema mais famoso do Corinthians?", "Timão, a torcida mais fiel"),
    criaCartao("Corinthians", "Quem é o técnico atual do Corinthians?", "Fernando Lázaro"),
    criaCartao("Corinthians", "Quem foi o jogador que mais vestiu a camisa do Corinthians?", "Cláudio"),
    criaCartao("Corinthians", "Em que ano o Corinthians foi campeão do Torneio Rio-São Paulo?", "2002"),
    criaCartao("Corinthians", "Qual é o nome do maior rival do Corinthians na Copa do Brasil?", "Flamengo"),
    criaCartao("Corinthians", "Qual jogador do Corinthians é conhecido como 'O Fenômeno'?", "Ronaldo")



